server:
  port: 9090

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:ORCL
#    username: TUANKIET
#    password: phamtuankiet
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: team2
    password: wibu123456


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.OracleDialect

  mail:
    host: smtp.gmail.com
    username: daido7031@gmail.com
    password: leerskmrmfogjnpx
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000

